version: "3.9"

services:
  nextapp:
    container_name: movies_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./public:/app/public
    environment:
      - API_END_POINT=${NEXT_PUBLIC_API_URL}
    networks:
      - movies_network

  postgres:
    container_name: movies_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - movies_network

networks:
  movies_network:

volumes:
  pgdata: