import type { Metadata } from "next";

import { Montserrat } from "next/font/google";

import ThemeProvider from "@core/providers/ThemeProvider";

const monserrat = Montserrat({
  subsets: ["latin"],
});

type TRootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: TRootLayoutProps) => {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
