import { dir } from "i18next";
import type { Metadata } from "next";

import { Montserrat } from "next/font/google";

import i18nConfig from "@core/configs/i18n";
import { TDefaultPageProps } from "@core/types";

import QueryProvider from "@core/providers/QueryProvider";
import ThemeProvider from "@core/providers/ThemeProvider";

const monserrat = Montserrat({
  subsets: ["latin"],
});

type TRootLayoutProps = Readonly<
  {
    children: React.ReactNode;
  } & TDefaultPageProps
>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const RootLayout = async ({ children, params }: TRootLayoutProps) => {
  const { locale } = await params;

  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={monserrat.className}>
        <QueryProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
